# Generated by Django 5.2 on 2026-02-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGearValueStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('max_rpm', models.FloatField()),
                ('min_rpm', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DataCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GearValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('channel', models.CharField(max_length=50)),
                ('rpm', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HourlyGearValueStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_start', models.DateTimeField(db_index=True)),
                ('max_rpm', models.FloatField()),
                ('min_rpm', models.FloatField()),
            ],
        ),
    ]
