# Generated by Django 5.2 on 2026-02-20 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygearvaluestats',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='gearvalue',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
