# Generated by Django 5.2 on 2025-05-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGearValueStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('max_rpm', models.FloatField()),
                ('min_rpm', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DataCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyGearValueStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_start', models.DateTimeField()),
                ('max_rpm', models.FloatField()),
                ('min_rpm', models.FloatField()),
            ],
        ),
    ]
