# Generated by Django 5.2 on 2026-02-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearapp', '0002_alter_dailygearvaluestats_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('input_rpm', models.FloatField()),
                ('output1_rpm', models.FloatField(blank=True, null=True)),
                ('output2_rpm', models.FloatField(blank=True, null=True)),
                ('output3_rpm', models.FloatField(blank=True, null=True)),
                ('output4_rpm', models.FloatField(blank=True, null=True)),
                ('ratio1', models.FloatField(blank=True, null=True)),
                ('ratio2', models.FloatField(blank=True, null=True)),
                ('ratio3', models.FloatField(blank=True, null=True)),
                ('ratio4', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
