# Generated by Django 5.2 on 2026-02-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearapp', '0003_gearratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearratio',
            name='output4_rpm',
        ),
        migrations.RemoveField(
            model_name='gearratio',
            name='ratio4',
        ),
        migrations.AlterField(
            model_name='gearvalue',
            name='channel',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
